config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :blog

  get 'home/index'
  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_recent_post
  protect_from_forgery with: :exception

  def load_recent_post
    @recent_posts = Article.order("created_at DESC").limit(4)
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog/index.html.erb
<!-- +++++ Posts Lists +++++ -->
<% @articles.each do |article| %>
 <div id= <%= article.id % 2  == 1 ? "grey" : "white" %>>
    <%= content_tag :div, class: "container" do%>
      <%= content_tag :div, class: "row" do %>
        <%= content_tag :div, class: "col-lg-8 col-lg-offset-2" do %>
          <p><%= image_tag "pp.png", class: "avatar-min" %></p>
          <bd><%= article.created_at.strftime("%B %d %Y")%></bd>
          <h4><%= article.title %></h4>
          <p><%= article.content.truncate(600)%></p>
          <p><%= link_to "Okumaya devam et...", blog_path(article) %></p>
        <%end%>
      <%end%>
    <%end%>
  </div>
<%end%>

app/views/blog/show.html.erb
<div id= <%= @article.id % 2  == 1 ? "grey" : "white" %>>
  <%= content_tag :div, class: "container" do%>
    <%= content_tag :div, class: "row" do %>
      <%= content_tag :div, class: "col-lg-8 col-lg-offset-2" do %>
        <p><%= image_tag "pp.png", class: "avatar-min" %></p>
        <p><%= @article.created_at.strftime("%B %d %Y")%></p>
        <h4><%= @article.title %></h4>
        <p><%= @article.content%></p>
        <p><%= link_to "Geri dön..", blog_index_path %></p>
      <%end%>
    <%end%>
  <%end%>
</div>

app/views/home/index.html.erb
<!-- +++++ Welcome Section +++++ -->
<div id="ww">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 centered">
        <%= image_tag "pp.png", id: "avatar" %>
        <h1>Merhaba, Ben Bertuğ!</h1>
        <p>Tam bir müzik aşığı birde bir kaç kodla beraber oldu deme keyfime!</p>

        <p>Zonguldak 1996 doğumlu, Celal Bayar Üniversitesi Yazılım Mühendisi adaylarından, James Hetfield dan amatör kendince profesyonel gitarist,
          beyazından siyah eksik olmayan BEŞİKTAŞ lı ,sporla uğraşmaktan deli gibi zevk alan arta kalan zamanlarında kitap okumak için can atan,
          yeri geldi mi neşeden çıldıran bir o kadarda ciddiyetine düşkün birisi düşünün işte o benim!</p>

        <!-- Links -->
        <%= content_tag :div, class: "row" do %>
          <%= link_to "https://github.com/bertugylmaz/", class: "social-icon" do %>
            <%= fa_icon "github 2x" %>
          <%end%>
          <%= link_to "https://www.linkedin.com/in/bertugyilmaz/", class: "social-icon" do %>
            <%= fa_icon "linkedin 2x" %>
          <%end%>
          <%= link_to "https://twitter.com/bertugylmaz", class: "social-icon" do %>
            <%= fa_icon "twitter 2x" %>
          <%end%>
          <%= link_to "https://www.instagram.com/bertugylmaz/", class: "social-icon" do %>
            <%= fa_icon "instagram 2x" %>
          <%end%>
          <%= mail_to "ylmazbertug@gmail.com", class: "social-icon" do %>
            <%= fa_icon "envelope-o 2x" %>
          <%end%>
        <%end%>

      </div><!-- /col-lg-8 -->
    </div><!-- /row -->
  </div> <!-- /container -->
</div><!-- /ww -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlogRuby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Bertuğ YILMAZ', home_index_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Hakkımda', root_path %></li>
            <li><%= link_to 'Blog', blog_index_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <%= yield %>

    <!-- +++++ Footer Section +++++ -->
    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h4>Son Paylaşılanlar</h4>
             <% @recent_posts.each do |article| %>
              <div class="row pl">
              <%= link_to article.title, blog_path(article)%>
              </div>
            <%end%>
          </div><!-- /col-lg-4 -->

          <div class="col-lg-6">
            <h4>BLOG'UM Hakkında</h4>
            <p>Bu web sayfasında tecrübe ettiğim teknolojiler, karşılaştığım sorunlar vb içerikler paylaşacağım.</p><br />
            <p></p>
          </div><!-- /col-lg-4 -->

        </div>
        <!-- <p>&copy BERTUĞ YILMAZ</p>-->
      </div>
    </div>

  </body>
</html>